### ISSUE TITLE
Error: Name systray is not defined!

### ISSUE THREAD

**Issue by notohh** [Tenrys/csgo_richpresence#4]
Title. Happens when i try and run the program manually, after it didnt work when i used the installer.

**Comment by Tenrys** [comment]
Was it with the executable or the Python script? As far as I know the dependencies should be bundled with the executable. If not then you need to install them manually, they are listed in the README. If you are trying to run it with the Python script you will need to install the dependencies yourself.

**Comment by notohh** [comment]
Its with the exec, csgo_richpresence.exe from the latest release.

**Comment by NetLuiz** [comment]
Yeah bro i have this error too, i'm using csgo_richpresence.exe

I have already installed Python's last version.

**Comment by OdarGM** [comment]
same

**Comment by Tenrys** [comment]
I'm working on rewriting this program in another language so it just works, and better, but for the time being try doing `pip install systray` and see what that changes.

**Comment by OdarGM** [comment]
I am getting some error  when i amd trying that command 
**Here is a gif** http://media.odar.xyz/d0L89WC4Kf.gif

**Comment by OdarGM** [comment]
and sure i will wait for the new update :D

**Comment by Tenrys** [comment]
Oops, try these commands instead. 
`pip install infi.systray`
`pip install win10toast`
`pip install PyVDF`
That should make it work. I'm not sure if the program itself works that well anymore though.

**Comment by uwx** [comment]
i think it's a limitation that the systray object is only created when silent mode is on and it's not assigned to anything by default so `if systray:` fails. i'm not a python expert though so i'm not 100% on it

**Comment by Tenrys** [comment]
That's exactly what the `if sistray:` bit is for, checking if it's assigned.

**Comment by uwx** [comment]
really? because i tried in the python repl just now:
![image](https://user-images.githubusercontent.com/13633343/40885930-e63334ec-6705-11e8-8945-0f2b2643134c.png)

however if you just initialized it to None:
![image](https://user-images.githubusercontent.com/13633343/40885940-fae28186-6705-11e8-99a2-ac64cd2cdc3d.png)

**Comment by Tenrys** [comment]
Well, it would be helpful if I got the line where the original error happens so I can tell where exactly it breaks and fix the error at least.

**Comment by Tenrys** [comment]
#5

**Comment by Tenrys** [comment]
Gonna close this for now, tell me if there is any more issues with the latest revision.
