### ISSUE TITLE
RPC Send Data

### ISSUE THREAD

**Issue by NetLuiz** [Tenrys/csgo_richpresence#6]
I have this error.

http://prntscr.com/jq8olv

**Comment by Tenrys** [comment]
Are you using Python 3.4?

**Comment by NetLuiz** [comment]
I'm using Python 3.6.5

**Comment by Tenrys** [comment]
¯\\\_(ツ)\_/¯
I'm not good at Python and this script kind of blows, so I suggest waiting for my other project `source-richpresence` to be in a ready state.
