### ISSUE TITLE
is this possible?

### ISSUE THREAD

**Issue by claire-rouge** [Tenrys/csgo_richpresence#7]
making it so when starting the rich presence you also start the game (idunno if its possible since steam game)

(like gw2 rich presence does https://gw2rpc.info/)

**Comment by claire-rouge** [comment]
and make it so when you die, you dont show the friendly's stats on ur discord when ur specating them when ded ingame, would be cool

**Comment by Tenrys** [comment]
Yeah, there's a lot of issues with this. I'll add something like OP for my new project.

**Comment by claire-rouge** [comment]
no problem, loving the rich presence so far, people can see how much I suck now :D

**Comment by Tenrys** [comment]
I'm more surprised you got it working

**Comment by claire-rouge** [comment]
hehe, have some people struggled to get the program working before?
the program even tells you what to do, the read me text that follows with also tells you what to do, its even stated in the manual(on the github site) where to place files for the rich presence to get ur stats lol 
![lul](https://user-images.githubusercontent.com/15875197/41804793-c52f0932-769c-11e8-95a3-f5e4a7cfc7b8.png)

if people struggle with this, they should have seen the creative ways to get ur music to be seen on discord before rich presence was a thing with python+snip 
![meguface](https://user-images.githubusercontent.com/15875197/41804799-eee4776c-769c-11e8-928e-2754f16d5c85.png)
just installing python and setting up the plugins the first time was harder than getting this program to start
![woop](https://user-images.githubusercontent.com/15875197/41804837-f1fc7c28-769d-11e8-9131-18d7362ee1a5.png)

**Comment by Tenrys** [comment]
It seemed like the script was broken for them or that the .exe had missing modules

**Comment by claire-rouge** [comment]
ah, I didnt have that problem, neither had a friend of mine that installed it yesterday
